// NEXORA pSEO guides dataset — problem-first diagnostic/decision guides, compiled June 2026.
// NEXORA-lane only (analytics/strategy/decisions), so the "NEXORA does this for you"
// card is honest. Each guide is a specific task with real steps — not a broad overview
// (those live in /blog), avoiding cannibalization. Unique steps/mistakes/faqs per guide
// keep every page genuinely useful, not thin.

export const guides = [
    {
      slug: 'why-did-my-youtube-views-drop',
      cluster: 'diagnostics',
      title: 'Why Did My YouTube Views Drop? A Step-by-Step Diagnostic (2026)',
      seoTitle: 'Why Did My YouTube Views Drop? (Fix It)',
      seoDescription: 'A step-by-step diagnostic for a sudden YouTube view drop in 2026 \u2014 rule out the outlier effect, find which traffic source slowed, and fix the real cause.',
      answer: 'A YouTube view drop is almost never a channel-wide penalty. Work it in order: rule out the outlier effect (a recent viral video fading to baseline), then open YouTube Studio and find which traffic source actually fell \u2014 Browse, Suggested, or Search. Each points to a different cause: CTR, satisfaction, or SEO. Fix that one thing, not everything.',
      intro: 'When views slide, the instinct is to change everything at once \u2014 new thumbnails, new topics, new schedule. That usually makes diagnosis impossible. The data in YouTube Studio already tells you which lane slowed and why; this walks you through reading it in the right order.',
      whatYouNeed: ['YouTube Studio access', 'Your last 90 days of analytics', '10 minutes'],
      steps: [
        { title: 'Rule out the outlier effect first', detail: 'If a recent video overperformed, the channel "drop" may just be views returning to your normal baseline. Zoom your analytics out to 6-12 months. If the line is flat-to-up over that window with one spike fading, nothing is wrong \u2014 you are comparing against an outlier.' },
        { title: 'Check whether it is normal fluctuation', detail: 'Compare this period to the same period last month and last year. Weekends, holidays, and seasonality move views by device and time of day. A 10-20% wobble week to week is noise, not a trend.' },
        { title: 'Find which traffic source dropped', detail: 'YouTube Studio \u2192 Analytics \u2192 Reach \u2192 Traffic sources. Identify the single lane that fell most: Browse (home/subscriptions), Suggested (next to other videos), or Search. Fixing the right lane beats changing everything randomly.' },
        { title: 'If Browse or Suggested fell, suspect CTR or satisfaction', detail: 'These lanes are algorithm-driven. A drop here usually means recent videos earned weaker clicks (CTR) or weaker watch satisfaction, so YouTube pulled back distribution. Check CTR and average view duration on your last 5 uploads.' },
        { title: 'If Search fell, suspect SEO or seasonality', detail: 'Search traffic slipping points to titles/descriptions going stale, a keyword getting more competitive, or seasonal demand fading. Check whether your search-driven videos are topical or evergreen.' },
        { title: 'Check upload consistency', detail: 'Erratic posting confuses both the audience habit loop and the algorithm\u2019s expectations. If your cadence broke in the weeks before the drop, that gap is a likely contributor.' },
        { title: 'Fix the one thing, then wait', detail: 'Change only the diagnosed cause, give it 1-2 weeks across several uploads, and compare the same metric before vs after. Changing five things at once means you will never know what worked.' },
      ],
      mistakes: [
        'Blaming a "shadowban" \u2014 YouTube does not silently penalize normal content; the algorithm just follows viewer behavior.',
        'Looking only at a 7-day window, where one faded outlier or a weekend distorts everything.',
        'Changing thumbnails, titles, topics, and schedule all at once so no cause is isolatable.',
        'Ignoring traffic sources and treating every drop as a single mysterious problem.',
      ],
      nexoraAngle: 'This whole diagnostic is what NEXORA runs automatically. Ask it "why did my views drop this week" and it compares your recent performance against your historical baseline, identifies which traffic source slowed, and tells you whether it is normal fluctuation or a real trend \u2014 in seconds instead of an hour of manual digging.',
      faqs: [
        { q: 'Did my YouTube views drop because of a shadowban?', a: 'Almost certainly not. YouTube has no generic shadowban for normal content. Views drop because viewers chose other videos (a CTR issue), clicked away early (a retention issue), or a recent outlier faded to baseline. The algorithm follows viewer behavior \u2014 it is not secretly punishing you. Diagnose the traffic source before assuming the worst.' },
        { q: 'How long should I wait before worrying about a view drop?', a: 'Give it two weeks and several uploads. Week-to-week swings of 10-20% are normal noise driven by seasonality, day of week, and whether a recent video overperformed. A real problem shows up as a sustained downward trend across multiple videos over a month \u2014 not a single slow week.' },
        { q: 'Why did my views drop even though my subscriber count went up?', a: 'Subscribers and views are loosely coupled. Most views come from Browse and Suggested, which depend on each video\u2019s CTR and satisfaction \u2014 not your subscriber number. You can gain subscribers while recent uploads underperform on clicks or retention, which pulls views down. Check your last few videos\u2019 CTR and average view duration.' },
      ],
    },
    {
      slug: 'thumbnail-or-video-ctr-vs-retention',
      cluster: 'diagnostics',
      title: 'Is It My Thumbnail or My Video? CTR vs Retention, Diagnosed',
      seoTitle: 'Thumbnail or Video? CTR vs Retention Fix',
      seoDescription: 'Low views but not sure why? Learn how to tell if it is a thumbnail/CTR problem or a content/retention problem in YouTube Studio \u2014 and fix the right one.',
      answer: 'Two numbers separate the two problems. If impressions are high but click-through rate is low (under ~3-4%), your thumbnail and title are the issue. If CTR is fine but average view duration is low, the content or hook is the issue. Check the Reach tab for CTR and the Engagement tab for retention before changing anything.',
      intro: 'Low views have two very different causes that need opposite fixes: people not clicking, or people clicking and leaving. Treating a retention problem like a thumbnail problem wastes weeks. Two metrics tell you which one you have.',
      whatYouNeed: ['YouTube Studio access', 'The underperforming video', '5 minutes'],
      steps: [
        { title: 'Open the video\u2019s Reach tab', detail: 'YouTube Studio \u2192 the video \u2192 Analytics \u2192 Reach. Note two numbers: impressions (how often YouTube showed it) and click-through rate (the share who clicked).' },
        { title: 'Read CTR against the healthy range', detail: 'A typical healthy CTR is 4-10% depending on niche and channel size. Below 3% with decent impressions means the thumbnail and title are not earning the click \u2014 that is your problem.' },
        { title: 'Open the Engagement tab', detail: 'Check average view duration (AVD) and the audience retention curve. A useful target is staying above ~50% of length at the 30-second mark and ~40% at the halfway point.' },
        { title: 'Locate the diagnosis', detail: 'High impressions + low CTR = thumbnail/title problem. Healthy CTR + low AVD or a steep early drop = content/hook problem. Low impressions overall is a third case \u2014 a discoverability/SEO problem, not packaging.' },
        { title: 'Fix only the diagnosed half', detail: 'If it is CTR, rework the thumbnail concept and title and let TubeBuddy-style A/B testing decide. If it is retention, fix the first 30 seconds and tighten pacing \u2014 leave the thumbnail alone.' },
      ],
      mistakes: [
        'Swapping the thumbnail when CTR was already fine and the real problem was a weak hook.',
        'Judging CTR without checking impressions \u2014 low impressions is a different (discoverability) problem.',
        'Reworking a video off one day of data instead of waiting for a stable sample.',
        'Chasing a 15% CTR \u2014 healthy is niche-dependent, and an inflated thumbnail that overpromises hurts retention.',
      ],
      nexoraAngle: 'NEXORA runs this split for you across every video at once. Instead of opening tabs per upload, you can ask which videos are losing views to weak CTR versus weak retention, and it flags each one with the metric that proves it \u2014 so you know exactly where to spend your editing time.',
      faqs: [
        { q: 'What is a good YouTube CTR in 2026?', a: 'For most channels, 4-10% is healthy, and it varies by niche and traffic source \u2014 Browse traffic often shows lower CTR than Search. Below 3% with solid impressions signals a thumbnail/title problem. Do not chase extreme numbers; a thumbnail that overpromises to inflate CTR usually tanks retention when the video cannot deliver.' },
        { q: 'My CTR is good but views are still low \u2014 why?', a: 'If CTR is healthy and views are still low, look at two things: impressions (if they are low, it is a discoverability/SEO problem, not packaging) and retention (if average view duration is weak, YouTube stops recommending after the initial test). Good CTR only converts impressions you actually receive.' },
        { q: 'Should I delete a video with low retention?', a: 'Usually no. A single low-retention video rarely drags a channel, and deleting loses any long-tail search value it has. Better to learn from it \u2014 find where the retention curve drops and fix that pattern in your next upload. Only consider unlisting if a video is actively misleading viewers and generating dissatisfaction signals.' },
      ],
    },
    {
      slug: 'find-hidden-gem-videos',
      cluster: 'opportunities',
      title: 'How to Find Your Hidden-Gem Videos (High Engagement, Low Reach)',
      seoTitle: 'Find Your Hidden-Gem YouTube Videos',
      seoDescription: 'Some of your videos have great engagement but never got shown to enough people. Learn how to find these hidden gems in YouTube Studio and give them a second life.',
      answer: 'A hidden gem is a video with strong engagement \u2014 high likes, comments, and average view duration \u2014 but low impressions, meaning YouTube under-distributed it. Find them by sorting your videos for high engagement rate and low reach. These are your best second-chance candidates: the content already works, it just never got shown.',
      intro: 'Most channels have a few videos that quietly outperformed on engagement but never got the impressions they deserved. They are the highest-leverage thing on your channel because the hard part \u2014 making content people love \u2014 is already done. You just have to surface them.',
      whatYouNeed: ['YouTube Studio access', 'Your full video library', '15 minutes'],
      steps: [
        { title: 'Pull engagement and reach side by side', detail: 'In YouTube Studio \u2192 Content, add columns or use Analytics to see, per video: average view duration, likes/comments relative to views, and impressions.' },
        { title: 'Flag high engagement + low impressions', detail: 'Look for videos where retention and engagement rate beat your channel average but impressions are below average. That mismatch is the hidden-gem signal \u2014 viewers loved it, YouTube barely showed it.' },
        { title: 'Confirm it is not a packaging fluke', detail: 'Open each candidate\u2019s Reach tab. If CTR is also strong, the only thing missing was distribution \u2014 a clean gem. If CTR was weak, it may have stalled in testing, which is a different fix.' },
        { title: 'Give the gem a second life', detail: 'Refresh the thumbnail and title to current standards, add it to a relevant playlist, link it from a newer popular video\u2019s end screen, and reference it in a community post. You are feeding it the impressions it never got.' },
        { title: 'Mine the pattern', detail: 'Hidden gems reveal topics or formats your audience loves but you under-made. Note what they have in common and make more of it deliberately.' },
      ],
      mistakes: [
        'Judging "best" videos by view count alone, which buries gems that never got distribution.',
        'Refreshing the thumbnail but not feeding the video new traffic from end screens or playlists.',
        'Treating a low-CTR video as a gem \u2014 if people did not click, it is a packaging problem, not a hidden gem.',
        'Finding the gem and never extracting the topic/format pattern behind it.',
      ],
      nexoraAngle: 'Hidden-gem detection is a built-in pattern in NEXORA. It cross-references engagement against reach across your whole library and surfaces the videos that overperformed on satisfaction but under-distributed \u2014 the exact list you would otherwise build by hand in a spreadsheet.',
      faqs: [
        { q: 'What counts as a "hidden gem" video?', a: 'A video whose engagement \u2014 average view duration, likes, and comments relative to views \u2014 beats your channel average, but whose impressions sat below average. It means viewers who found it loved it, but YouTube never distributed it widely. That gap makes it a strong candidate to revive, because the content quality is already proven.' },
        { q: 'Can I really get more views on an old video?', a: 'Yes, more often than creators expect. A refreshed thumbnail and title, a spot in a relevant playlist, an end-screen link from a current popular video, and a community post can feed an under-distributed video the impressions it missed. It works best on evergreen topics; a time-sensitive video has a harder ceiling.' },
        { q: 'How is a hidden gem different from a video that just flopped?', a: 'Engagement. A flop usually shows weak retention or weak CTR \u2014 viewers did not click or did not stay. A hidden gem shows the opposite: strong retention and engagement, just starved of impressions. Same low view count, opposite cause, opposite fix.' },
      ],
    },
    {
      slug: 'why-did-my-video-flop',
      cluster: 'diagnostics',
      title: 'Why Did My Video Flop? A Single-Video Post-Mortem',
      seoTitle: 'Why Did My YouTube Video Flop?',
      seoDescription: 'A step-by-step post-mortem for one underperforming YouTube video \u2014 isolate whether it was the topic, the packaging, or the content using YouTube Studio.',
      answer: 'A single flopped video failed at one of three gates: distribution (low impressions = topic/SEO or a cold start), clicks (impressions fine, CTR low = packaging), or retention (CTR fine, AVD low = content). Open the video\u2019s Reach and Engagement tabs and find which gate it failed \u2014 that is the lesson, not the view count.',
      intro: 'One flop is not a channel problem, but it is a free lesson if you read it right. The view count tells you nothing; the gate it failed at tells you everything. This isolates which one so your next video does not repeat it.',
      whatYouNeed: ['YouTube Studio access', 'The specific video', '10 minutes'],
      steps: [
        { title: 'Check impressions first', detail: 'Reach tab \u2192 impressions. If they are far below your usual, YouTube barely tested it \u2014 a topic, SEO, or cold-start problem. The video may not have failed on quality at all; it failed to get shown.' },
        { title: 'If impressions were normal, check CTR', detail: 'Normal impressions but low CTR (under ~3%) means the thumbnail and title did not earn the click. The algorithm offered it and viewers passed.' },
        { title: 'If CTR was fine, check retention', detail: 'Healthy CTR but low average view duration means people clicked and left. Open the retention curve and find where they dropped \u2014 a weak hook shows as a cliff in the first 30 seconds.' },
        { title: 'Compare to a similar past winner', detail: 'Put the flop next to a video on a similar topic that worked. The metric that differs most is the cause. This controls for niche and channel size.' },
        { title: 'Write the one-line lesson', detail: 'Reduce it to a single sentence: "failed on CTR" or "lost them at 0:20." Carry that into the next upload. A flop you can name is worth more than a hit you cannot explain.' },
      ],
      mistakes: [
        'Concluding "the algorithm killed it" without checking which gate it actually failed.',
        'Comparing the flop to a viral outlier instead of a normal video on a similar topic.',
        'Reading retention before confirming the video even got impressions and clicks.',
        'Deleting it immediately and losing both the data and any long-tail search value.',
      ],
      nexoraAngle: 'NEXORA does single-video post-mortems on demand. Point it at a video and it isolates the failure gate \u2014 distribution, clicks, or retention \u2014 and compares the video against your own similar uploads to explain what differed, so the lesson is explicit instead of a guess.',
      faqs: [
        { q: 'Is one flopped video bad for my channel?', a: 'No. A single underperformer does not penalize your channel \u2014 YouTube evaluates videos largely on their own merits, and recommends each based on its viewer signals. What matters is whether a pattern of flops shares a cause. One flop is a data point; learn the gate it failed and move on.' },
        { q: 'Should I delete a video that flopped?', a: 'Usually not. Deleting loses the analytics lesson and any slow search traffic the video might accumulate over time. The exception is a video that actively misleads viewers and generates dissatisfaction. Otherwise, leave it up, learn from it, and let evergreen topics keep earning trickle views.' },
        { q: 'How do I know if it was the topic or the execution?', a: 'Impressions tell you. Low impressions point to a topic/SEO/cold-start issue \u2014 YouTube never found an audience to test it on. Normal impressions shift the blame to execution: low CTR is packaging, low retention is content. The Reach tab separates "nobody saw it" from "people saw it and passed."' },
      ],
    },
    {
      slug: 'find-next-video-idea-from-analytics',
      cluster: 'strategy',
      title: 'How to Find Your Next Video Idea From Your Own Analytics',
      seoTitle: 'Find Your Next Video Idea From Data',
      seoDescription: 'Stop guessing topics. Learn how to mine your own YouTube analytics for your next video idea \u2014 using your overperformers, retention spikes, and audience signals.',
      answer: 'Your best next idea is usually hiding in your own data. Find your overperforming videos, the topics with the strongest retention, and the comments asking follow-up questions. Make the next video an extension of what already worked for your specific audience \u2014 a proven angle beats a guessed one.',
      intro: 'Generic idea generators give you what works for everyone, which is rarely what works for you. Your analytics already show what your audience rewards. This turns that into a repeatable way to pick the next topic instead of staring at a blank screen.',
      whatYouNeed: ['YouTube Studio access', 'Your top videos and comments', '20 minutes'],
      steps: [
        { title: 'List your top overperformers', detail: 'Sort by views relative to your average, not absolute views. Find the videos that beat your channel\u2019s baseline by the widest margin \u2014 those topics struck a nerve.' },
        { title: 'Check retention on each winner', detail: 'A high-view video with weak retention won on packaging, not substance. A winner with strong retention means the topic itself delivered \u2014 those are the ones to extend.' },
        { title: 'Mine the comments for follow-up demand', detail: 'On your winners, read the comments for "can you do a video on..." and recurring questions. That is your audience telling you the next topic, already validated by interest.' },
        { title: 'Find adjacent angles, not repeats', detail: 'Take a proven topic and shift one variable: a deeper dive, the opposite take, a beginner version, or the next step. You are reusing demand without remaking the same video.' },
        { title: 'Sanity-check against external demand', detail: 'Before committing, confirm the angle has search or trend interest beyond your channel so it can pull new viewers, not just your existing ones.' },
      ],
      mistakes: [
        'Ranking ideas by absolute views, which just favors your oldest videos with the most lifetime time to accumulate.',
        'Extending a high-view, low-retention video \u2014 you would be scaling a packaging trick, not a topic people loved.',
        'Ignoring the comments, which are the cheapest validated-demand source you have.',
        'Remaking the exact same video instead of shifting one variable for a fresh angle.',
      ],
      nexoraAngle: 'NEXORA generates content ideas from exactly this analysis \u2014 your overperformers, your retention patterns, and what is working for similar creators \u2014 and returns each idea with a format and a viral-potential read. It is the data-driven version of this workflow, not a generic idea list.',
      faqs: [
        { q: 'Why are data-driven video ideas better than generic AI ideas?', a: 'Because they are validated against your specific audience. A generic idea generator returns what trends broadly; your analytics show what your viewers actually reward \u2014 which topics they finish, which they share, which they ask follow-ups about. An idea anchored to a proven overperformer on your channel carries far less risk than one pulled from a generic list.' },
        { q: 'How do I pick which of my successful topics to repeat?', a: 'Prioritize winners with strong retention, not just high views. High views with weak retention means the thumbnail did the work and the topic did not land \u2014 repeating it scales a trick. High views with strong retention means the subject itself delivered, so an adjacent angle on it is your safest bet.' },
        { q: 'Should I just remake my most popular video?', a: 'Shift one variable instead of remaking it. Take the proven topic and go deeper, take the opposite stance, make a beginner or advanced version, or cover the logical next step. You reuse the demand that made the original work without publishing a near-duplicate that competes with itself.' },
      ],
    },
    {
      slug: 'find-best-posting-time-from-data',
      cluster: 'strategy',
      title: 'How to Find Your Best Posting Time From Your Own Data',
      seoTitle: 'Find Your Best YouTube Posting Time',
      seoDescription: 'Generic "best time to post" advice is useless. Learn how to find YOUR channel\u2019s best posting time from your own YouTube analytics \u2014 when your audience is actually online.',
      answer: 'Ignore generic best-time charts. Open YouTube Studio \u2192 Audience \u2192 "When your viewers are on YouTube" to see your specific audience\u2019s active hours, then cross-reference which of your past uploads performed best by day and time. Post a few hours before your audience\u2019s peak so the video is ready when they arrive.',
      intro: 'Every "best time to post on YouTube" article gives you an average for strangers. Your audience has its own rhythm, and your own analytics show it precisely. This finds the window that actually fits your viewers.',
      whatYouNeed: ['YouTube Studio access', 'A few months of uploads', '10 minutes'],
      steps: [
        { title: 'Open your audience activity chart', detail: 'YouTube Studio \u2192 Analytics \u2192 Audience \u2192 "When your viewers are on YouTube." This shows the days and hours your specific subscribers are active.' },
        { title: 'Cross-reference your own upload performance', detail: 'List your past videos by upload day and time, with their first-48-hour views. Patterns emerge \u2014 some channels see a clear day or slot that consistently outperforms.' },
        { title: 'Post ahead of the peak, not during it', detail: 'Upload a few hours before your audience\u2019s active window so YouTube has time to index and the video is ready to surface when viewers arrive, rather than dropping it mid-peak.' },
        { title: 'Account for time zones', detail: 'If your audience spans regions, the chart reflects a blend. Aim for the window that covers your largest geographic cluster, which you can confirm in the Audience geography report.' },
        { title: 'Test and lock it in', detail: 'Try your candidate slot for several uploads and compare first-48-hour views against your old timing. Once a slot wins consistently, make it your default and keep cadence regular.' },
      ],
      mistakes: [
        'Following a generic "best time to post" chart built from other people\u2019s audiences.',
        'Posting exactly at peak instead of a few hours ahead, leaving no indexing runway.',
        'Changing posting time every week, so no slot ever gets a fair test.',
        'Optimizing time while ignoring consistency \u2014 a regular cadence matters more than the perfect hour.',
      ],
      nexoraAngle: 'NEXORA reads your audience-activity data and your own upload performance to recommend specific posting times \u2014 down to the day and hour, with the average views and engagement each slot has produced for you. It is the manual cross-reference above, done from your real numbers.',
      faqs: [
        { q: 'What is the actual best time to post on YouTube?', a: 'There is no universal answer \u2014 the right time is whenever your specific audience is active, which your analytics show under "When your viewers are on YouTube." Generic charts average millions of unrelated channels and rarely match your viewers. Post a few hours before your audience\u2019s peak so the video is live and indexed when they arrive.' },
        { q: 'Does posting time even matter on YouTube?', a: 'It matters less than content and consistency, but it gives early uploads a fair shot. A strong first 24-48 hours helps a video pass YouTube\u2019s initial testing, and that window depends on your audience being online to click and watch. Timing is a tiebreaker, not a growth strategy on its own.' },
        { q: 'Should I post at the same time every week?', a: 'A consistent cadence helps. It builds an audience habit and sets the algorithm\u2019s expectation for new content. Pick the best-performing slot from your data and keep it stable; erratic timing weakens the early engagement that new uploads depend on.' },
      ],
    },
    {
      slug: 'spot-a-video-taking-off-early',
      cluster: 'opportunities',
      title: 'How to Spot a Video Taking Off Early (and Ride the Spike)',
      seoTitle: 'Spot a YouTube Video Taking Off Early',
      seoDescription: 'Learn the early YouTube Studio signals that a video is about to take off \u2014 rising VPH, climbing CTR, growing Suggested traffic \u2014 and how to capitalize before the spike fades.',
      answer: 'A video that is taking off shows rising views-per-hour, steady or climbing CTR as impressions scale, and a growing share of Browse or Suggested traffic. When you see those together in the first 24-72 hours, the algorithm is widening distribution \u2014 capitalize by feeding it: pin a comment, add end screens, and prep a follow-up.',
      intro: 'Most creators notice a breakout days after the window to act on it closed. The early signals are visible within hours in YouTube Studio, and a breakout is the rare moment where small actions compound. Knowing what to watch lets you ride it instead of just watching it happen.',
      whatYouNeed: ['YouTube Studio access', 'A recent upload (first 72 hours)', 'Real-time analytics'],
      steps: [
        { title: 'Watch views-per-hour in real time', detail: 'YouTube Studio \u2192 the video \u2192 real-time. Rising or sustained views-per-hour well above your channel norm is the first sign the algorithm is leaning in.' },
        { title: 'Confirm CTR holds as impressions scale', detail: 'A breakout shows impressions climbing while CTR stays steady or rises. If CTR holds as YouTube shows it to broader audiences, distribution will keep widening.' },
        { title: 'Watch for Browse and Suggested share growing', detail: 'A take-off is driven by algorithmic lanes, not just your subscribers. If Browse and Suggested are claiming a growing share of traffic, the video is escaping your existing audience \u2014 the key breakout signal.' },
        { title: 'Feed the spike immediately', detail: 'Pin an engaging comment to lift interaction, make sure end screens and cards point to your best related video to capture session time, and reply to early comments to boost engagement signals while the window is open.' },
        { title: 'Prep the follow-up now', detail: 'A breakout proves demand for that exact topic right now. Start the adjacent follow-up while the spike is live so you publish into existing momentum instead of after it fades.' },
      ],
      mistakes: [
        'Noticing the breakout days later, after the distribution window already narrowed.',
        'Changing the thumbnail or title mid-spike and resetting the momentum.',
        'Letting end screens point nowhere, wasting the session time a breakout sends you.',
        'Failing to prep a follow-up, so the proven demand evaporates before you publish again.',
      ],
      nexoraAngle: 'NEXORA flags outlier videos \u2014 uploads performing well above your channel average \u2014 so a breakout surfaces while you can still act on it. Pair that alert with the steps above and you catch the spike in its first hours instead of reading about it in next month\u2019s recap.',
      faqs: [
        { q: 'How early can you tell if a YouTube video will go viral?', a: 'Often within the first 24-72 hours. The tells are rising views-per-hour above your norm, CTR holding steady as impressions scale, and Browse/Suggested traffic claiming a growing share. No signal guarantees virality, but those three moving together mean the algorithm is actively widening distribution \u2014 the moment to act.' },
        { q: 'Should I change anything on a video that is taking off?', a: 'Do not touch the thumbnail or title \u2014 changing packaging mid-breakout can reset the momentum YouTube is rewarding. Instead, feed it: pin a comment, reply to viewers to lift engagement, point end screens at your best related video to capture session time, and start the follow-up. Amplify, do not alter.' },
        { q: 'What is views-per-hour and where do I find it?', a: 'Views-per-hour (VPH) is how fast a video is accumulating views right now, visible in YouTube Studio\u2019s real-time view. It is the most responsive early signal of a breakout because it reacts within hours, long before daily totals or the standard analytics tabs show the trend.' },
      ],
    },
    {
      slug: 'which-content-format-to-make-more-of',
      cluster: 'strategy',
      title: 'How to Figure Out Which Content Format to Make More Of',
      seoTitle: 'Which YouTube Format to Make More Of',
      seoDescription: 'Long-form, Shorts, tutorials, vlogs \u2014 which format actually works for your channel? Learn how to run a content-mix analysis on your own data and double down right.',
      answer: 'Run a content-mix analysis: group your videos by format (long-form, Shorts, tutorial, vlog, etc.) and compare each group\u2019s average views, retention, and subscribers gained \u2014 not raw totals. The format with the best per-video averages and subscriber pull is where to invest, even if another format has more total views from sheer volume.',
      intro: 'Channels often spread effort evenly across formats out of habit, when the data shows one format does most of the work. A content-mix analysis tells you where your effort actually pays, so you stop subsidizing formats that quietly underperform.',
      whatYouNeed: ['YouTube Studio access', 'Your video library', '20 minutes'],
      steps: [
        { title: 'Tag every video by format', detail: 'Group your uploads into clear buckets \u2014 long-form, Shorts, tutorial, vlog, listicle, whatever fits your channel. Be consistent so the comparison is clean.' },
        { title: 'Compare averages, not totals', detail: 'For each format, calculate average views per video, not total views. Totals just reward whichever format you have made most of. Averages reveal which format performs per unit of effort.' },
        { title: 'Layer in retention and subscribers gained', detail: 'A format can pull views but few subscribers, or vice versa. Check average view duration and subscribers gained per format \u2014 some formats grow the channel, others only entertain.' },
        { title: 'Weigh effort against return', detail: 'Factor production cost. If long-form averages 3x the views of Shorts but takes 6x the time, Shorts may be the better return \u2014 or the reverse. Return per hour, not just per video.' },
        { title: 'Rebalance deliberately', detail: 'Shift your mix toward the format with the best return and subscriber pull, while keeping enough of the others to stay discoverable. Re-run the analysis quarterly as your channel evolves.' },
      ],
      mistakes: [
        'Comparing total views by format, which just reflects how many of each you have published.',
        'Optimizing for views while ignoring which format actually gains subscribers.',
        'Dropping a format entirely instead of rebalancing \u2014 Shorts and long-form often feed each other.',
        'Running the analysis once and never revisiting it as the audience changes.',
      ],
      nexoraAngle: 'Content-mix analysis is a native NEXORA pattern. It breaks your library down by format and shows, for example, that long videos average far more views than Shorts on your channel \u2014 or the opposite \u2014 with the retention and subscriber data behind each, so the rebalancing decision is grounded in your numbers.',
      faqs: [
        { q: 'Should I focus on Shorts or long-form YouTube videos?', a: 'It depends on your channel\u2019s data, not the general trend. Compare the average views, retention, and subscribers gained per video for each format on your own channel. Shorts often win on reach but convert fewer long-term subscribers; long-form usually builds deeper loyalty but costs more to make. Many channels use Shorts to feed discovery and long-form to retain.' },
        { q: 'Why compare averages instead of total views by format?', a: 'Totals just reward whichever format you have made the most of \u2014 if you have 200 Shorts and 20 long-form videos, Shorts will "win" on totals regardless of quality. Average views per video controls for that and shows which format actually performs per unit of effort, which is what your production time should follow.' },
        { q: 'How often should I redo a content-mix analysis?', a: 'Roughly quarterly, or after any major format experiment. Audience preferences and YouTube\u2019s surfaces shift over time, and a format that underperformed six months ago may work now. Re-running it keeps your mix aligned with what your current audience rewards rather than a stale snapshot.' },
      ],
    },
    {
      slug: 'reverse-engineer-competitor-best-videos',
      cluster: 'strategy',
      title: 'How to Reverse-Engineer a Competitor\u2019s Best-Performing Videos',
      seoTitle: 'Reverse-Engineer Competitor YouTube Videos',
      seoDescription: 'Learn how to analyze a competitor\u2019s YouTube channel the right way \u2014 find their overperformers, decode the pattern, and find the gap you can fill instead of copying.',
      answer: 'Pick 3-5 channels near your size, then find each one\u2019s overperformers \u2014 videos that beat their own channel average, spotted via views-per-hour and view counts well above their norm. Decode what those videos share (topic, angle, packaging), then find the gap they are not covering. The goal is to learn the pattern and differentiate, not clone.',
      intro: 'Competitor analysis goes wrong in two ways: copying their videos, or ignoring them entirely. The useful middle is reverse-engineering why their best videos worked and spotting what they are missing. This is how you borrow proven demand without becoming a worse version of someone else.',
      whatYouNeed: ['3-5 competitor channels', 'A free tool like Social Blade or vidIQ', '30 minutes'],
      steps: [
        { title: 'Pick the right competitors', detail: 'Choose 3-5 channels within roughly 2-3x your subscriber count in your niche. Channels far bigger than you play a different game; same-size channels reveal what is winnable now.' },
        { title: 'Find their overperformers', detail: 'Scan each channel for videos with views well above their channel average. A free views-per-hour signal (vidIQ\u2019s extension) or visible view counts highlight which recent videos broke out for them.' },
        { title: 'Decode the shared pattern', detail: 'Across their overperformers, look for what repeats: a topic angle, a title structure, a thumbnail style, a format. The pattern \u2014 not any single video \u2014 is the insight.' },
        { title: 'Find the gap', detail: 'Note what every competitor is doing the same way. Uniformity is opportunity: an angle, depth, or audience segment none of them serves is where you differentiate instead of competing head-on.' },
        { title: 'Adapt, do not clone', detail: 'Take the proven pattern and apply your own angle, expertise, or audience. Borrow the demand signal; bring something they cannot \u2014 your perspective or a gap they ignore.' },
      ],
      mistakes: [
        'Studying channels 10x your size whose strategies do not transfer to your stage.',
        'Copying a competitor\u2019s exact video instead of decoding the pattern behind their wins.',
        'Looking at their average videos instead of isolating their genuine overperformers.',
        'Trusting Social Blade earnings estimates as fact \u2014 they can be off by 3-5x.',
      ],
      nexoraAngle: 'NEXORA does competitor analysis by handle \u2014 point it at a channel and it surfaces what is working there and how it compares to your own data. Because it knows your channel too, it frames the competitor\u2019s wins against your actual position, which is the part a manual scan cannot do.',
      faqs: [
        { q: 'How do I analyze a competitor\u2019s YouTube channel?', a: 'Pick 3-5 channels near your size, find each one\u2019s overperformers (videos well above their own average, visible via view counts or a views-per-hour tool), and decode what those winners share \u2014 topic, title pattern, thumbnail style. Then look for the gap none of them covers. The point is to learn the pattern and differentiate, not to copy their uploads.' },
        { q: 'Which competitors should I study \u2014 big channels or my size?', a: 'Your size, mostly. Channels within 2-3x your subscriber count reveal what is actually winnable at your stage; their wins are reproducible for you. Channels 10x bigger operate with audience scale, budgets, and algorithm trust you do not have yet, so their strategies often will not transfer cleanly.' },
        { q: 'Are Social Blade competitor numbers accurate?', a: 'The subscriber and view trends are directionally fine; the earnings estimates are not. Social Blade guesses revenue from public views and a generic CPM range, so figures can be off by 3-5x in either direction. Use it for growth direction and benchmarking, never quote its earnings as fact.' },
      ],
    },
    {
      slug: 'set-realistic-youtube-view-goals',
      cluster: 'strategy',
      title: 'How to Set Realistic View Goals for Your Channel',
      seoTitle: 'Set Realistic YouTube View Goals',
      seoDescription: 'Stop comparing yourself to giant channels. Learn how to set realistic YouTube view goals by benchmarking against your own baseline and similar-size channels in your niche.',
      answer: 'Set goals against two baselines: your own recent average (aim to beat your trailing 10-video average by a sensible margin) and similar-size channels in your niche (within 2-3x your subscriber count). A video doing 1,000 views is a win for a 500-subscriber channel and a miss for a 100K one \u2014 context defines realistic.',
      intro: 'View goals pulled from thin air either crush your morale or let you off too easy. Realistic goals come from two reference points you can actually measure: where you have been, and what comparable channels achieve. This sets targets that motivate instead of mislead.',
      whatYouNeed: ['YouTube Studio access', '2-3 comparable channels', '15 minutes'],
      steps: [
        { title: 'Establish your own baseline', detail: 'Calculate your trailing 10-video average views (exclude any obvious outlier). That number is your honest starting line \u2014 goals are movements from it, not arbitrary round numbers.' },
        { title: 'Benchmark similar-size channels', detail: 'Find 3-5 niche channels within 2-3x your subscriber count. Note their typical per-video views. This shows what is achievable at your stage in your niche, which raw aspiration cannot.' },
        { title: 'Set a stretch-but-reachable target', detail: 'Aim to beat your baseline by a margin that is meaningful but plausible \u2014 not 10x. Sustainable goals compound; impossible ones just produce burnout when you miss them.' },
        { title: 'Separate input goals from outcome goals', detail: 'You control inputs (upload cadence, improving CTR, tightening hooks), not outcomes (exact view counts). Set input goals you own and treat views as the lagging result.' },
        { title: 'Review and reset monthly', detail: 'As your baseline rises, raise the bar. Goals that never move stop being useful; recalibrating monthly keeps them honest and motivating.' },
      ],
      mistakes: [
        'Benchmarking against channels 10-100x your size and feeling like a failure for normal results.',
        'Setting only outcome goals (view counts) you cannot directly control.',
        'Including a viral outlier in your baseline, which sets an unbeatable bar.',
        'Never revisiting goals, so they drift out of touch with your actual trajectory.',
      ],
      nexoraAngle: 'NEXORA frames your performance against your own baseline and your niche automatically, so "is this video good?" gets a contextual answer instead of a raw number. It knows your trailing averages and flags when a result is genuinely strong for your stage \u2014 the benchmark step above, built in.',
      faqs: [
        { q: 'How many views should my YouTube video get?', a: 'There is no universal number \u2014 it depends on your channel size and niche. A useful benchmark is your own trailing 10-video average plus what similar-size channels (within 2-3x your subscribers) typically get. A thousand views can be a strong result for a 500-subscriber channel and a weak one for a channel with 100K, so judge against your context, not a global figure.' },
        { q: 'Why shouldn\u2019t I compare my channel to big creators?', a: 'Because their results are unreproducible at your stage. Large channels have audience scale, algorithm trust, budgets, and brand recognition you have not built yet. Benchmarking against them sets impossible goals and corrodes motivation. Channels within 2-3x your size show what is actually winnable now, which is the only comparison that informs realistic goals.' },
        { q: 'Should I set goals based on views or something else?', a: 'Set input goals you control \u2014 upload consistency, improving CTR, tightening your hook \u2014 and treat views as the lagging outcome. You cannot will a view count into existence, but you can reliably execute the inputs that produce it. Input goals keep you focused on what actually moves the result.' },
      ],
    },
    {
      slug: 'audit-your-title-performance',
      cluster: 'strategy',
      title: 'How to Audit Your Title Performance (Which Titles Actually Win)',
      seoTitle: 'Audit Your YouTube Title Performance',
      seoDescription: 'Find out which title styles actually earn clicks on your channel \u2014 run a title audit against your own CTR data instead of guessing or copying generic title formulas.',
      answer: 'Audit titles by pairing each video\u2019s title style with its CTR, not its views. Group your titles by pattern \u2014 how-to, listicle, question, curiosity, number-led \u2014 and compare average CTR per group. The patterns with the highest CTR are what your specific audience clicks; make more titles in those shapes and drop the ones that consistently underperform.',
      intro: 'Title advice online is a pile of contradictory formulas. The only formula that matters is the one your audience clicks, and your CTR data already ranks them. A title audit replaces guessing with your own evidence.',
      whatYouNeed: ['YouTube Studio access', 'Your videos with CTR data', '20 minutes'],
      steps: [
        { title: 'Pull CTR per video', detail: 'For each recent video, note its title and its impressions click-through rate from the Reach tab. CTR, not views, isolates how the title and thumbnail earned the click.' },
        { title: 'Tag each title by pattern', detail: 'Group titles into styles: how-to, listicle ("7 ways..."), question, curiosity gap, number-led, direct/keyword. Consistency makes the comparison meaningful.' },
        { title: 'Compare average CTR by pattern', detail: 'Average the CTR within each style group. A clear winner usually emerges \u2014 your audience clicks certain shapes more reliably than others, regardless of what works for other channels.' },
        { title: 'Control for the thumbnail', detail: 'CTR is title and thumbnail combined. Where possible, compare videos with similar thumbnail quality so you are reading the title\u2019s contribution, not the image\u2019s.' },
        { title: 'Standardize on your winners', detail: 'Write future titles in your highest-CTR patterns, keep them specific and benefit-led, and retire the styles that consistently underperform for you. Re-audit every couple of months.' },
      ],
      mistakes: [
        'Auditing titles by views instead of CTR \u2014 views fold in distribution and retention, muddying the title\u2019s real effect.',
        'Copying a generic title formula that tested well on a channel nothing like yours.',
        'Ignoring the thumbnail\u2019s role and crediting CTR entirely to the title.',
        'Writing vague curiosity titles ("You won\u2019t believe...") that underperform specific, benefit-led ones.',
      ],
      nexoraAngle: 'NEXORA analyzes title performance as a pattern across your channel \u2014 including subtler signals like title length or language. On one channel it surfaced that a specific title language drove far higher average views; that is the kind of pattern a manual audit can miss but a model reading all your data catches.',
      faqs: [
        { q: 'Should I audit titles by views or CTR?', a: 'CTR. Views bundle in distribution and retention, so a high-view video might have had a mediocre title carried by a great topic or strong push. Click-through rate isolates how well the title and thumbnail earned the click from the impressions YouTube gave it \u2014 which is exactly what a title audit should measure.' },
        { q: 'What makes a good YouTube title in 2026?', a: 'Specific, benefit-led, and curiosity-balanced. A title that implies a clear answer or payoff ("I tested 50 thumbnails and here\u2019s what got clicks") beats a vague tease ("You won\u2019t believe this"). But "good" is channel-specific \u2014 audit your own CTR by title pattern, because the shape your audience clicks may differ from any generic rule.' },
        { q: 'How do I separate the title\u2019s effect from the thumbnail?', a: 'Compare videos with similar thumbnail quality so the image is roughly constant and CTR differences trace to the title. It is never perfectly clean \u2014 CTR is always the title and thumbnail together \u2014 but grouping by comparable thumbnails, or A/B testing titles with the thumbnail fixed, isolates the title\u2019s contribution well enough to act on.' },
      ],
    },
    {
      slug: 'find-which-videos-bring-subscribers',
      cluster: 'opportunities',
      title: 'How to Find Which Videos Actually Bring You Subscribers (Not Just Views)',
      seoTitle: 'Which Videos Bring YouTube Subscribers',
      seoDescription: 'High views do not always mean new subscribers. Learn how to find which of your YouTube videos actually convert viewers into subscribers \u2014 and make more of them.',
      answer: 'Views and subscribers are different outcomes. In YouTube Studio, check "Subscribers" as a metric per video (Analytics \u2192 Audience, or the Subscribers column) to see which videos drove the most new subscribers \u2014 not which got the most views. The high-converting videos reveal what makes someone commit, which is the content worth repeating to grow.',
      intro: 'A video can rack up views and add almost no subscribers, while a smaller video quietly converts viewers into fans. If you only chase views, you can grow a channel that no one commits to. This finds the videos that actually build your audience.',
      whatYouNeed: ['YouTube Studio access', 'Your video library', '15 minutes'],
      steps: [
        { title: 'Pull subscribers gained per video', detail: 'YouTube Studio \u2192 Analytics \u2192 Content or Audience, and surface "Subscribers" per video. This is a separate metric from views \u2014 it shows net new subscribers each video drove.' },
        { title: 'Compare against views', detail: 'Put subscribers-gained next to views per video. Look for the mismatches: high views/low subs (entertaining but not committing) and modest views/high subs (deeply resonant). The second group is gold.' },
        { title: 'Decode the high-converters', detail: 'Study the videos that punched above their view count on subscribers. They usually share something \u2014 depth, a clear promise of more, a strong personal angle, or a series hook \u2014 that makes a viewer want the next one.' },
        { title: 'Check where converters sit in the journey', detail: 'Some videos convert because they are great entry points for new viewers; others convert loyal returnees. Use traffic sources to see whether your converters pull new audiences or deepen existing ones \u2014 you want more of the former for growth.' },
        { title: 'Make more of what commits', detail: 'Prioritize the formats and topics that convert, and add clear "subscribe for the rest of this" hooks to videos like them. Optimizing for commitment compounds; optimizing for raw views often does not.' },
      ],
      mistakes: [
        'Judging every video by views and never looking at subscribers gained at all.',
        'Doubling down on a high-view, low-conversion format that entertains but never builds an audience.',
        'Ignoring whether converters attract new viewers or just re-engage existing fans.',
        'Adding generic "please subscribe" asks instead of a reason tied to more of that specific content.',
      ],
      nexoraAngle: 'NEXORA reads subscribers-gained alongside views across your library, so the videos that actually convert surface without a manual cross-reference. Because it analyzes the pattern, it can tell you which topics and formats turn viewers into subscribers for your channel specifically \u2014 the difference between growing views and growing an audience.',
      faqs: [
        { q: 'Why do my videos get views but no subscribers?', a: 'Views and subscriptions measure different things. A video can earn views through a catchy thumbnail or a one-off trending topic without giving viewers a reason to commit to more. Subscribers come from resonance \u2014 depth, a clear promise of similar content, or a personality people want to follow. Check subscribers-gained per video to find which content actually converts, and make more of it.' },
        { q: 'Where do I see how many subscribers a video gained?', a: 'In YouTube Studio under Analytics \u2192 Audience, or by adding the Subscribers metric per video. It shows net subscribers each video drove, separate from its view count. That separation is the whole point \u2014 it reveals the videos that build your audience versus the ones that merely entertain and move on.' },
        { q: 'Should I optimize for views or subscribers?', a: 'For long-term growth, weight subscribers and the loyalty behind them. Views are a leading signal, but subscribers are recurring audience \u2014 they return, watch longer, and give new uploads a stronger start. The ideal video does both, but if you must choose what to make more of, follow the content that converts viewers into committed subscribers.' },
      ],
    },
  ]